### ISSUE TITLE
COVID-19: Revise Ask Us options

### ISSUE THREAD

**Issue by tomkeays** [tomkeays/lemoyne#61]
We decided to deprecate 

- Ask Us by Phone
- Ask Us in Person

and replace with

- Ask Us by Appointment

which is essentially a reformatting of the in person option, with some new text.

**Tasks**

- [x] Redo the pages on https://resources.library.lemoyne.edu/askus/ to reflect the new structure
- [x] The above includes the LibraryH3lp FAQ, which shares the same menu - https://ask.library.lemoyne.edu/
- [x] Set redirects in LibGuides for the two deprecated pages
- [x] Map new Ask Us by Appointment box onto Contact Us page and hide old box - https://resources.library.lemoyne.edu/contact
- [x] Redo the banner menus including
  - [x] LibGuides
  - [x] LibCal
  - [x] LibraryH3lp FAQ
  - [x] WebPac
  - [x] 360 Link Journal Finder
  - [x] 360 Link Citation Linker
  - [x] Wordpress
- [x] Update the master Ask Us widgets housed here - https://resources.library.lemoyne.edu/askus/widgets
  - [x] new SVG icon for Ask Us By Appointment on master widgets (a calendar icon)

**Comment by tomkeays** [comment]
To Do
- new SVG icon for Ask Us By Appointment on master widgets (a calendar icon)
- update banners
  - Wordpress
  - 360 Link Journal Finder
  - 360 Link Citation Linker

**Comment by tomkeays** [comment]
Because it had been about 2 years since I had to modify the headers in Serials Solutions (Ex Libris or whatever you want to call it) and because the interface is a real rats nest, I documented what files go where in LibGuides <https://resources.library.lemoyne.edu/staff/technology/web-branding/ex-libris>. SerSol is also annoying because, even though I updated the banner and other files today, it won't go live until tomorrow.

**Comment by tomkeays** [comment]
All the banners are updated. I am going to close this issue, but the plan is to update the LibGuide (mentioned in previous comment) for all of the web sites.
